
version: '3.8'
services:
  movies:
    image: 6302626032/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: 6302626032/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: 6302626032/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: 6302626032/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
~
~

